config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :lists do
    post :favorite, on: :member
    resources :tasks do
      patch :completed, on: :member
      patch :incomplete, on: :member
    end
  end

  get '/users/:user_id/favorites' => "users/favorites#index", as: :user_favorite_lists
  delete '/users/:user_id/favorites/:id' => "users/favorites#destroy", as: :remove_from_favorites

  get 'public_lists' => "home#public_lists"

  root "home#index"
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :list

  validates_uniqueness_of :user_id, :scope => [:user_id, :list_id], message: "A Lista já está marcada como favorita."
  validates_presence_of :list_id

  validate :list_must_be_public


  def list_must_be_public
    unless list.opened?
      errors.add(:base)
    end
  end

end

app/models/list.rb
class List < ActiveRecord::Base
	has_many :tasks, dependent: :destroy
  has_many :favorites
  belongs_to :user

  validates :user_id, presence: true
  validates :title, presence: true

  scope :ordered, -> { order('created_at ASC') }
  scope :publics, -> { where(opened: true).order('created_at DESC') }
  scope :last_public_lists, -> { publics.limit(3) }
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :list
  validates :description, presence: true

  def completed?
  	finished_at.present?
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :trackable, :validatable

  has_many :lists
  has_many :favorites

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  protected
    def authenticate_user!
      redirect_to root_path, notice: "Cadastre-se ou faça login para continuar." unless user_signed_in?
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!
  def index
    @public_lists = List.last_public_lists
  end

  def public_lists
    @public_lists = List.publics.paginate(:page => params[:page], :per_page => 6)
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  def show
    @list ||= List.find_by(id: params[:id], opened: true)
  end

  def new
    @list = List.new
  end

  def edit
  end

  def create
    @list = current_user.lists.new(list_params)

    if @list.save
      redirect_to @list, notice: 'Lista de tarefas criada com sucesso.'
    else
      render :new
    end
  end

  def update
    if @list.update(list_params)
      redirect_to @list, notice: 'Lista atualizada.'
    else
      render :edit
    end
  end

  def favorite
    @favorite_list = Favorite.new(list_id: params[:id], user: current_user)

    if @favorite_list.save!
      flash[:notice] = "A lista foi adicionada aos favoritos"
    else
      flash[:error] = "Um erro aconteceu ao tentar adicionar a lista aos favoritos :("
    end
    redirect_to public_lists_url
  end

  def destroy
    @list.destroy
    redirect_to root_url, notice: 'Lista excluída.'
  end

  private
    def set_list
      @list = current_user.lists.find_by_id(params[:id])
    end

    def list_params
      params.require(:list).permit(:title, :opened)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
	before_action :set_list
	before_action :set_task, except: :create

	def new
	end

	def create
		@task = @list.tasks.create(tasks_params)
 		respond_to do |format|
      format.html { redirect_to(@list) }
      format.js
    end
	end

	def destroy
		if @task.destroy
			flash[:success] = "Tarefa excluída :)"
		else
			flash[:error] = "Erro ao tentar excluir a tarefa :("
		end

		redirect_to @list
	end

	def completed
		@task.update_attribute(:finished_at, Time.zone.now)
		redirect_to @list, notice: "Boooa! :)"
	end

	def incomplete
		@task.update_attribute(:finished_at, nil)
		redirect_to @list
	end

	private

		def set_task
			@task = @list.tasks.find(params[:id])
		end

	  def set_list
	  	@list = List.find(params[:list_id])
	  end

		def tasks_params
	   	params.require(:task).permit(:description)
	  end
end

app/controllers/users/favorites_controller.rb
class Users::FavoritesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_favorite, only: :destroy

  def index
    @favorites = current_user.favorites
  end

  def destroy
    if @favorite.destroy
      flash[:notice] = "Removido dos favoritos"
    else
      flash[:notice] = "Erro ao tentar remover lista dos favoritos"
    end

    redirect_to public_lists_url
  end

  private

    def set_favorite
      @favorite = current_user.favorites.find_by(list_id: params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def is_a_favorite_list?(list_id, user_id)
    Favorite.where(user_id: user_id, list_id: list_id).present?
  end
end

app/helpers/lists_helper.rb
module ListsHelper
	def list_privacy_image
		if @list.opened
      image_tag('list/unlocked.png', title: "Pública")
    else
      image_tag('list/locked.png', title: "Privada")
    end
	end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/home/_lists.html.erb
<% @public_lists.each do |list| %>
  <div class="row list-item">
      <%= link_to list.title, list %> <span>|</span> <%= time_ago_in_words(list.created_at) %>
      <% if current_user %>
        <% if is_a_favorite_list?(list.id, current_user.id) %>
          <%= link_to image_tag('list/favorite.png', title: "Remover das favoritas"), remove_from_favorites_path(list.user_id, list.id), method: :delete, :id => "unfav-list" %>
        <% else %>
          <%= link_to image_tag('list/nofavorite.png', title: "Marcar como favorita"), favorite_list_path(list), method: :post, :id => "fav-list" %>
        <% end %>
      <% end %>
  </div>
<% end %>

app/views/home/index.html.erb
<% if user_signed_in? %>
  <div class="row"><%= render "users/lists" %></div>

<% else %>
  <div>
    <div class="row">
      <%= simple_form_for(:user, url: session_path(:user)) do |f| %>
          <%= f.hint "Acesse sua conta" %>
          <%= f.input :email, inline_label: true, label: false, placeholder: "Seu email", required: false, autofocus: true %>
          <%= f.input :password, label: false, placeholder: "Sua senha", required: false %>
          <%= f.button :submit, "Acessar", :class => 'btn sign_in', :id => 'user_login' %>
      <% end %>
    </div>

     <div  class="row">
      <h3>Organize e compartilhe suas listas de tarefas.</h3>
      <%= render 'lists' %>
     </div>

    <div class="center-content">
      <%= link_to "Cadastre-se", new_user_registration_path, :class => 'btn sign_up' %>
    </div>
  </div>
<% end %>

app/views/home/public_lists.html.erb
<div class="row">
  <h2>Listas Públicas</h2>
</div>
<div class="row">
  <%= render 'lists' %>
</div>
<div class="row">
  <%= will_paginate @public_lists %>

  <%= link_to 'Voltar', root_path, :class => 'btn' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todolist</title>
  <link href='http://fonts.googleapis.com/css?family=Raleway:300' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="container">

  <div class="row">
    <% if user_signed_in? %>
      <span>
        <%= link_to "Minhas listas", root_path %>
      </span>
      <span>
        <%= link_to "Públicas", public_lists_path %>
      </span>
      <span>
        <%= link_to 'Favoritas', user_favorite_lists_path(current_user), :id => 'user_favorites' %>
      </span>
      <span>
        Olá, <%= current_user.email %> |
          <%= link_to "Sair", destroy_user_session_path, :method => :delete %>
      </span>
    <% end %>
  </div>

  <div class="row">
    <p id="notice"><%= notice %></p>
  </div>

  <%= yield %>

</body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for @list do |f| %>
  <div class="row">
    <%= f.hint "Título" %>
    <%= f.input :title, label: false %>
  </div>
  <div class="row">
    <%= f.hint "Pública?" %>
    <%= f.input :opened, label: false, as: :boolean %>
  </div>
  <div class="row">
    <%= f.button :submit, "Salvar", :class => 'btn new-list', :id => "save-list" %>
    <%= link_to 'Voltar', root_path, :class => 'btn btn-back' %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h2>Editar Lista de Tarefas</h2>

<%= render 'form' %>

app/views/lists/new.html.erb
<h2>Nova Lista</h2>

<%= render 'form' %>

app/views/lists/show.html.erb
<div class="row">
  <h3><%= @list.title %> - <%= list_privacy_image %></h3>
</div>

<div id="new-task-item">
  <%= render @list.tasks %>
</div>

<div class="row">
  <%= render "tasks/form" %>
</div>

app/views/tasks/_form.html.erb
<%= simple_form_for([@list, Task.new], remote: true) do |f| %>
  <div class="row">
    <%= f.input :description, label: false, placeholder: "nova tarefa...", :class => 'input-new-task', :id => "task_description" %>
  </div>
  <div class="row">
  	<%= f.submit  "Adicionar Tarefa", :class => 'btn new-task', :data => "create-task", :id => "save-task" %>
    <%= link_to 'Voltar', :back, :class => 'btn btn-back' %>
  </div>

<% end %>

app/views/tasks/_task.html.erb
<div class="row task-item">
	<% if task.completed? %>
		<strike><%= task.description %></strike>
	<% else %>
		<%= task.description %>
	<% end %>

	<% if task.completed? %>
		<%= link_to "Desfazer", incomplete_list_task_path(@list, task.id), :id => 'todo-task', method: :patch %>
	<% else %>
		<%= link_to "Concluído", completed_list_task_path(@list, task.id), :id => 'todo-task', method: :patch %>
	<% end %>

  <%= link_to image_tag('list/delete.png', title: "Excluir"), list_task_path(@list, task.id), method: :delete, data: { confirm: "Você tem certeza?"} %>
</div>

app/views/tasks/create.js.erb
$("#task_description").val("");
$("#new-task-item").empty().append("<%= j render @list.tasks %>");

app/views/users/_lists.html.erb
<h2>Minhas Listas</h2>

<% current_user.lists.ordered.each do |list| %>
  <div class="row list-item">
    <%= link_to list.title, list %>
    <%= link_to image_tag('list/delete.png', title: "Excluir"), list, method: :delete, data: { confirm: 'Você tem certeza?' } %>
    <%= link_to image_tag('list/edit.png', title: "Editar"), edit_list_path(list) %>
  </div>
<% end %>

<div class="row">
  <%= link_to "Nova lista", new_list_path, :class => 'btn', :id => 'new-list' %>
</div>

app/views/users/favorites/index.html.erb
<div class="row">
  <h2>Minhas Listas Favoritas</h2>

  <% @favorites.each do |fav| %>
    <div class="row list-item">
      <%= link_to fav.list.title, fav.list %>
      <%= link_to image_tag('list/favorite.png', title: "Remover dos favoritos"), remove_from_favorites_path(fav.list.user_id, fav.list.id), method: :delete %>
    </div>
  <% end %>
  <br/>
  <br/>
  <div class="row">
    <%= link_to 'Voltar', root_path, :class => 'btn' %>
  </div>
</div>